// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The navigation tree of the Orion Platform documentation. It is defined
 * explicitly rather than autogenerated, so the labels and the order stay
 * independent of file names, and every section keeps its own overview page.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Home',
    },
    {
      type: 'category',
      label: 'Introduction',
      description:
        'What Orion is, how the platform is built, which component owns which responsibility, and what the terms in this documentation mean.',
      link: {type: 'doc', id: 'introduction/index'},
      items: [
        {
          type: 'doc',
          id: 'introduction/what-is-orion',
          label: 'What is Orion Platform',
        },
        {type: 'doc', id: 'introduction/architecture', label: 'Architecture'},
        {type: 'doc', id: 'introduction/glossary', label: 'Glossary'},
      ],
    },
    {
      type: 'category',
      label: 'Getting started',
      description:
        'Requirements, installation with Docker or Kubernetes, configuration, and your first order created through the API in under an hour.',
      link: {type: 'doc', id: 'getting-started/index'},
      items: [
        {
          type: 'doc',
          id: 'getting-started/requirements',
          label: 'Requirements',
        },
        {
          type: 'category',
          label: 'Installation',
          link: {type: 'doc', id: 'getting-started/installation/index'},
          items: [
            {
              type: 'doc',
              id: 'getting-started/installation/docker',
              label: 'Docker Compose',
            },
            {
              type: 'category',
              label: 'Kubernetes',
              link: {
                type: 'doc',
                id: 'getting-started/installation/kubernetes/index',
              },
              items: [
                {
                  type: 'doc',
                  id: 'getting-started/installation/kubernetes/helm',
                  label: 'Helm',
                },
                {
                  type: 'doc',
                  id: 'getting-started/installation/kubernetes/operator',
                  label: 'Operator',
                },
              ],
            },
            {
              type: 'doc',
              id: 'getting-started/installation/bare-metal',
              label: 'System packages',
            },
          ],
        },
        {
          type: 'category',
          label: 'Configuration',
          link: {type: 'doc', id: 'getting-started/configuration/index'},
          items: [
            {
              type: 'doc',
              id: 'getting-started/configuration/environment-variables',
              label: 'Environment variables',
            },
            {
              type: 'doc',
              id: 'getting-started/configuration/profiles',
              label: 'Profiles',
            },
          ],
        },
        {
          type: 'doc',
          id: 'getting-started/first-order',
          label: 'First order',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      description:
        'Authentication, event processing, migrations between releases, and multi-tenancy in a single installation.',
      link: {type: 'doc', id: 'guides/index'},
      items: [
        {
          type: 'category',
          label: 'Authentication',
          link: {type: 'doc', id: 'guides/authentication/index'},
          items: [
            {
              type: 'doc',
              id: 'guides/authentication/oauth2',
              label: 'OAuth2 client credentials',
            },
            {
              type: 'doc',
              id: 'guides/authentication/api-keys',
              label: 'API keys',
            },
            {
              type: 'doc',
              id: 'guides/authentication/roles-and-permissions',
              label: 'Roles and permissions',
            },
          ],
        },
        {
          type: 'category',
          label: 'Events',
          link: {type: 'doc', id: 'guides/events/index'},
          items: [
            {
              type: 'doc',
              id: 'guides/events/queues',
              label: 'Queues and topics',
            },
            {
              type: 'doc',
              id: 'guides/events/retries',
              label: 'Retries and idempotency',
            },
          ],
        },
        {
          type: 'category',
          label: 'Migrations',
          link: {type: 'doc', id: 'guides/migrations/index'},
          items: [
            {
              type: 'doc',
              id: 'guides/migrations/from-3-8-to-4-2',
              label: 'From 3.8 LTS to 4.2 LTS',
            },
          ],
        },
        {type: 'doc', id: 'guides/multi-tenancy', label: 'Multi-tenancy'},
      ],
    },
    {
      type: 'category',
      label: 'API',
      description:
        'REST API reference, webhooks including signature verification, and the official client libraries for Java and Python.',
      link: {type: 'doc', id: 'api/index'},
      items: [
        {
          type: 'category',
          label: 'REST',
          link: {type: 'doc', id: 'api/rest/index'},
          items: [
            {
              type: 'category',
              label: 'Resources',
              items: [
                {
                  type: 'doc',
                  id: 'api/rest/resources/customers',
                  label: 'Customers',
                },
                {
                  type: 'doc',
                  id: 'api/rest/resources/orders',
                  label: 'Orders',
                },
                {
                  type: 'doc',
                  id: 'api/rest/resources/payments',
                  label: 'Payments',
                },
              ],
            },
            {
              type: 'doc',
              id: 'api/rest/pagination',
              label: 'Pagination and filtering',
            },
            {
              type: 'doc',
              id: 'api/rest/rate-limits',
              label: 'Rate limits',
            },
            {
              type: 'doc',
              id: 'api/rest/error-codes',
              label: 'Error codes',
            },
          ],
        },
        {
          type: 'category',
          label: 'Webhooks',
          link: {type: 'doc', id: 'api/webhooks/index'},
          items: [
            {
              type: 'doc',
              id: 'api/webhooks/event-types',
              label: 'Event types',
            },
            {
              type: 'doc',
              id: 'api/webhooks/signature-verification',
              label: 'Signature verification',
            },
          ],
        },
        {
          type: 'category',
          label: 'Client libraries',
          link: {type: 'doc', id: 'api/sdk/index'},
          items: [
            {type: 'doc', id: 'api/sdk/java', label: 'Java'},
            {type: 'doc', id: 'api/sdk/python', label: 'Python'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      description:
        'Monitoring, alerts, backups, scaling, security, and runbooks for on-call engineers.',
      link: {type: 'doc', id: 'operations/index'},
      items: [
        {
          type: 'category',
          label: 'Monitoring',
          link: {type: 'doc', id: 'operations/monitoring/index'},
          items: [
            {
              type: 'doc',
              id: 'operations/monitoring/metrics',
              label: 'Metrics',
            },
            {type: 'doc', id: 'operations/monitoring/logs', label: 'Logs'},
            {type: 'doc', id: 'operations/monitoring/alerts', label: 'Alerts'},
          ],
        },
        {type: 'doc', id: 'operations/backups', label: 'Backups'},
        {
          type: 'doc',
          id: 'operations/scaling',
          label: 'Scaling and performance',
        },
        {type: 'doc', id: 'operations/security', label: 'Security'},
        {
          type: 'category',
          label: 'Runbooks',
          link: {type: 'doc', id: 'operations/runbooks/index'},
          items: [
            {
              type: 'doc',
              id: 'operations/runbooks/database-outage',
              label: 'PostgreSQL outage',
            },
            {
              type: 'doc',
              id: 'operations/runbooks/queue-backlog',
              label: 'Event queue backlog',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Help',
      description:
        'Frequently asked questions, the release changelog, and the support contact channels.',
      items: [
        {type: 'doc', id: 'faq', label: 'FAQ'},
        {type: 'doc', id: 'changelog', label: 'Changelog'},
        {type: 'doc', id: 'support', label: 'Support'},
      ],
    },
  ],
};

export default sidebars;
